const strings = {
  appTitle: "My Database Management App",
  persons: "Persons",
  archive: "Archive",
  callsLog: "Calls Log",
  dispatch: "Dispatch",
  search: "Search",
  name: "Name",
  phoneNumber: "Phone Number",
  actions: "Actions",
  view: "View",
  edit: "Edit",
  addPerson: "Add Person",
  // Archive Table
  T: "T",
  phoneNumber: "Phone Number",
  nameInfo: "Name Info",
  bookId: "Book ID",
  appBookDate: "App Book Date",
  receivedFrom: "Received From",
  accusedChar: "Accused Character",
  appForm: "App Form",
  appDate: "App Date",
  periodFromTo: "Period From/To",
  techName: "Tech Name",
  appKind: "App Kind",
  // Calls Log (a_temp)
  eReport: "E Report",
  callerNumber: "Caller Number",
  calledNumber: "Called Number",
  thirdPartyNumber: "Third Party Number",
  callInitialTime: "Call Initial Time",
  conversationDuration: "Conversation Duration",
  city: "City",
  siteName: "Site Name",
  chargedMobileUserIMEI: "Charged Mobile User IMEI",
  chargedMobileUserIMSI: "Charged Mobile User IMSI",
  lon: "Longitude",
  lat: "Latitude",
  siteID: "Site ID",
  cgi: "CGI",

  // Calls Log (z_temp)
  date: "Date",
  callType: "Call Type",
  duration: "Duration",
  callingNumber: "Calling Number",
  callLocation: "Call Location",
  split: "Split",

  // Calls Log (k_temp)
  datetime: "Date/Time",
  msisdn: "MSISDN",
  imsi: "IMSI",
  bPartyMSISDN: "B-Party MSISDN",
  callingNumber: "Calling Number",
  calledNumber: "Called Number",
  imei: "IMEI",
  callLocation: "Call Location",
  site: "Site",
  governorate: "Governorate",
  longitude: "Longitude",
  latitude: "Latitude",

  // Dispatch Table
  nameAccused: "Name of Accused",
  savedNumbers: "Saved Numbers",
  savedName: "Saved Name",
  savedInfo: "Saved Info",
  city: "City",
};

export default strings;
